/*******************************************************************************
* Copyright 2011 See AUTHORS file.
*
* Licensed under the Apache License, Version 2.0 (the "License");

* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*

* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,

* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and

* limitations under the License.
******************************************************************************/

#include <jni.h>
#include <jni_md.h>
#include <stdlib.h>
#include <stdio.h>
#include "SimpleConvertImage.h"   // this header file was generated by javah

JNIEXPORT jbyteArray JNICALL Java_SimpleConvertImage_process
  (JNIEnv *env, jclass obj, jbyteArray byte_array){
	int i ;
	jsize byte_array_len = env->GetArrayLength(byte_array);

	int len = env->GetArrayLength (byte_array);
    unsigned char* buf = new unsigned char[len];
    env->GetByteArrayRegion (byte_array, 0, len, reinterpret_cast<jbyte*>(buf));
    int j;
    for (j = 90	; j < byte_array_len; j+=3){       
	buf[j] = buf[j+1];
        buf[j+2] = buf[j+1];
    }
    
    jbyteArray array = env->NewByteArray (byte_array_len);
    env->SetByteArrayRegion (array, 0, byte_array_len, reinterpret_cast<jbyte*>(buf));
    return array;

	}
