/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleConvertImage */

#ifndef _Included_SimpleConvertImage
#define _Included_SimpleConvertImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimpleConvertImage
 * Method:    process
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SimpleConvertImage_process
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
